diary/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('users.urls')),
    path('admin/', admin.site.urls),
    path('diary/', include('personalDiary.urls'))
]

personalDiary/urls.py
from django.urls import path
from .views import DeleteDairyView, ListDiaryView, CreateDiaryView, UpdateDiaryView, DetailDiaryView, DeleteDairyView

app_name='personalDiary'
urlpatterns = [
    path('', ListDiaryView.as_view(), name='home'),
    path('<int:pk>/', DetailDiaryView.as_view(), name='detail-diary'),
    path('new-diary/', CreateDiaryView.as_view(), name='new-diary'),
    path('<int:pk>/update', UpdateDiaryView.as_view(), name='update-diary'),
    path('<int:pk>/delete', DeleteDairyView.as_view(), name='delete-diary')
]

users/urls.py
from django.urls import path, include
from .views import index, register, index

app_name = 'users'
urlpatterns = [
    path('', index),
    path('account/', include('django.contrib.auth.urls')),
    path('register_new/', register, name='register')
]

personalDiary/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.urls import reverse
from django.contrib.auth.models import User
class Diary(models.Model):
    NORMAL = 'n'
    HAPPY = 'h'
    SAD = 's'
    MOOD_CHOICES = [
        (NORMAL, 'Normal'),
        (HAPPY, 'Happy'),
        (SAD, 'Sad')
    ]
    user = models.ForeignKey(User, verbose_name=_("User"), on_delete=models.CASCADE, null=True)
    title = models.CharField(_("title"), max_length=50)
    body = models.TextField(_("diary body"))
    mood = models.CharField(_("mood"), max_length=50, choices=MOOD_CHOICES, default=NORMAL)
    created = models.DateTimeField(_("diary created date"), auto_now_add=True)
    updated = models.DateTimeField(_("diary updated date"), auto_now=True)


    def get_absolute_url(self):
        return reverse("personalDiary:detail-diary", kwargs={"pk": self.pk})
    
    def __str__(self):
        name = 'no one' if self.user is None else self.user.username
        return f'{name} - {self.title}'

users/models.py
from django.db import models

# Create your models here.

personalDiary/forms.py
from django.db.models import fields
from django.forms import ModelForm
from .models import Diary

class DiaryForm(ModelForm):
    class Meta:
        model=Diary
        fields='__all__'

users/forms.py
from django.contrib.auth.forms import UserCreationForm


class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        fields = UserCreationForm.Meta.fields + ("email", )

personalDiary/views.py
from django.shortcuts import render
from django.views.generic import FormView
from django.urls import reverse_lazy
from django.views.generic import DetailView, UpdateView, DeleteView, ListView, CreateView

from .forms import DiaryForm
from .models import Diary
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required, permission_required
from django.utils.decorators import method_decorator
from django.core.exceptions import PermissionDenied


APP_NAME = "personalDiary"
def set_template_name(template_name):
    return f"{APP_NAME}/{template_name}"


class ListDiaryView(ListView):
    context_object_name='diaries'

    def get_queryset(self):
        user = self.request.user
        if user.is_anonymous:
            raise PermissionDenied
        user_ins = User.objects.get(username=self.request.user.username)
        return Diary.objects.filter(user=user_ins).all()


class CreateDiaryView(CreateView):
    model=Diary
    fields=['title', 'body', 'mood']
    template_name='personalDiary/new_diary.html'


    #* must user login 
    def get(self, request, *args, **kwargs):
        user = request.user
        if user.is_anonymous:
            raise PermissionDenied
        return super().get(request)

    def post(self, request, *args, **kwargs):
        user = request.user
        if user.is_anonymous:
            raise PermissionDenied
        return super().post(request)

    def form_valid(self, form):
        form.instance.user=self.request.user
        return super().form_valid(form)


class DetailDiaryView(DetailView):
    model=Diary

    def get(self, request, *args, **kwargs):
        user = request.user
        if user.is_anonymous:
            raise PermissionDenied
        return super().get(request)

class UpdateDiaryView(UpdateView):
    model=Diary
    fields=['title', 'body']
    # success_url=reverse_lazy('detail-diary')

    #* must user login 
    def get(self, request, *args, **kwargs):
        user = request.user
        if user.is_anonymous:
            raise PermissionDenied

class DeleteDairyView(DeleteView):
    model=Diary
    success_url=reverse_lazy('personalDiary:home')

    #* must user login 
    def get(self, request, *args, **kwargs):
        user = request.user
        if user.is_anonymous:
            raise PermissionDenied
    

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.urls.base import reverse
from .forms import CustomUserCreationForm

def index(request):
    #! view function in django should not return string just http response.
    if request.user.is_authenticated:
        return redirect(reverse('personalDiary:home'))
    return redirect(reverse('users:login'))


def register(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect(reverse('personalDiary:home'))
        return render(request, 'users/register.html', context={'form': form})
    form = CustomUserCreationForm()
    return render(request, 'users/register.html', context={'form': form})

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>Personal Diary</title>
</head>
<body>
    <header>
        <h1 id="logo">Diary Workspace😉</h1>
    </header>
    <div class="container">
        {% block content %}
        {% endblock content %}
    </div>
</body>
</html>

templates/personalDiary/diary_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        <h3>Delete the "{{ object.title }}" note from the diary?</h3>
        <button class="del-btn" type="submit">Yes</button> <a class="inline-btn" href="{% url 'personalDiary:detail-diary' object.id %}">No</a>
    </form>
{% endblock content %}

templates/personalDiary/diary_detail.html
{% extends 'base.html' %}
{% block content %}
<a class='btn-dark' href="{% url 'personalDiary:home' %}">&larr; Take me back</a>
<br>
<h3 class='title3' >{{ object.title }}</h3>
<p class='body'>{{ object.body }}</p>
<div class='btns-container'>
<a href="{% url 'personalDiary:update-diary' object.id %}">Edit</a> <a href="{% url 'personalDiary:delete-diary' object.id %}">Delete</a>
</div>
{% endblock content %}

templates/personalDiary/diary_form.html
{% extends 'base.html' %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Update</button>
    </form>
{% endblock content %}

templates/personalDiary/diary_list.html
{% extends 'base.html' %}

{% block content %}
    <div id="user-control">
        <h2>Hello, {{ request.user }}</h2>
        <p><a href="{% url 'users:logout' %}">Logout</a></p>
    </div>
    <p id='add-diary-nav'>Add <a href="{% url 'personalDiary:new-diary' %}">New</a> diary</p>
    <ul id='notes-list'>
        {% if diaries %}
        {% for diary  in diaries %}
            <li><span class="note-date">{{ diary.created |date}}</span><a href="{% url 'personalDiary:detail-diary' diary.id %}">{{ diary.title }}</a></li>    
        {% endfor %}
        {% else %}
            <p>Oppp! You hvae not write any diary!</p>
        {% endif %}
    </ul>
{% endblock content %}

templates/personalDiary/home.html
{% extends 'base.html' %}

{% block content %}
    <h2>Hello, {{ request.user }}</h2>
    <p><a href="{% url 'users:logout' %}">Logout</a></p>
    <ul id='notes-list'>
        {% if diaries %}
        {% for diary  in diaries %}
            <li><span class="note-date">{{ diary.created |date}}</span><a href="{% url 'personalDiary:detail-diary' diary.id %}"><h3>{{ diary.title }}</h3></a></li>    
        {% endfor %}
        {% else %}
            <p>Oppp! You hvae not write any diary!</p>
        {% endif %}
    </ul>
{% endblock content %}

templates/personalDiary/new_diary.html
{% extends 'base.html' %}

{% block content %}
    <form action="." method="post">
        <h3>New Diary</h3>
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Go</button>
    </form>
{% endblock content %}

templates/users/register.html
{% extends 'base.html' %}

{% block content %}
<form method="post" id="register-form">
    <h3>Register</h3>
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Register">
</form>

<a style="display: block; margin-top: 1rem; color: inherit; text-decoration: none; text-align: center;" class="inline-btn" href="{% url 'users:login' %}">Back to login</a>
{% endblock %}